name: Write dependency locks
on:
  pull_request_target:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # All history for all branches and tags.
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up OpenJDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: "temurin"
        cache: "gradle"
    - name: Write dependency locks
      run: ./gradlew checkDependencies --write-locks
    - name: Print the difference after writing dependency locks
      run: git diff --name-only HEAD --
    - id: diff
      name: Check for updates in dependency locks
      run: echo "updates=$(git diff --name-only HEAD -- | wc -l)" >> "$GITHUB_OUTPUT"
    - if: ${{ steps.diff.outputs.updates != '0' }}
      name: Push the updates in dependency locks
      run: |
        git config --local user.email "${{ vars.DEPENDABOT_COMMITTER_EMAIL }}"
        git config --local user.name "${{ vars.DEPENDABOT_COMMITTER_NAME }}"
        git commit --all --message="Update gradle.lockfile"
        git push -u origin HEAD:${{ github.head_ref }}
